"""task(-language +language_id)

Revision ID: 1c79ecd250d3
Revises: 6d4fc7be0741
Create Date: 2020-11-03 14:29:43.037689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c79ecd250d3'
down_revision = '6d4fc7be0741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('language_id', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'language_id')
    # ### end Alembic commands ###
