"""Add date_delivery in Solutions

Revision ID: 312430cac8bc
Revises: 
Create Date: 2020-10-01 00:01:18.518883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312430cac8bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('solutions', sa.Column('date_delivery', sa.DateTime(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'date_delivery')
    # ### end Alembic commands ###
