"""ondelete add

Revision ID: 61d836515120
Revises: bbf6f8e96127
Create Date: 2020-11-04 00:55:34.440592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d836515120'
down_revision = 'bbf6f8e96127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('solutions_task_id_fkey', 'solutions', type_='foreignkey')
    op.create_foreign_key(None, 'solutions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submissions_submissions_batch_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'submissions_batch', ['submissions_batch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submissions_batch_solution_id_fkey', 'submissions_batch', type_='foreignkey')
    op.create_foreign_key(None, 'submissions_batch', 'solutions', ['solution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tasks_lesson_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_lesson_id_fkey', 'tasks', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'submissions_batch', type_='foreignkey')
    op.create_foreign_key('submissions_batch_solution_id_fkey', 'submissions_batch', 'solutions', ['solution_id'], ['id'])
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_submissions_batch_id_fkey', 'submissions', 'submissions_batch', ['submissions_batch_id'], ['id'])
    op.drop_constraint(None, 'solutions', type_='foreignkey')
    op.create_foreign_key('solutions_task_id_fkey', 'solutions', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
