"""submissions

Revision ID: 69f00d6deeb7
Revises: 1c79ecd250d3
Create Date: 2020-11-03 16:34:11.468851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f00d6deeb7'
down_revision = '1c79ecd250d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_sub', sa.String(), nullable=True),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.String(), nullable=True),
    sa.Column('stderr', sa.String(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('memory', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    # ### end Alembic commands ###
