"""Task(+task_count)

Revision ID: 6d4fc7be0741
Revises: 8c83cc9c08db
Create Date: 2020-11-02 05:35:05.080327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4fc7be0741'
down_revision = '8c83cc9c08db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tries_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tries_count')
    # ### end Alembic commands ###
