"""tasks: -(in_data, out_data, type_check), +(api_check(bool), examples(array(json)), solution(text));

Revision ID: 87935a2868c7
Revises: 
Create Date: 2020-10-25 14:05:59.548443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87935a2868c7'
down_revision = '315cb5435237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('api_check', sa.Boolean()))
    op.add_column('tasks', sa.Column('examples', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('tasks', sa.Column('examples_hidden', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('tasks', sa.Column('solutions', sa.Text(), nullable=True))
    op.drop_column('tasks', 'out_data')
    op.drop_column('tasks', 'type_check')
    op.drop_column('tasks', 'in_data')
    op.drop_constraint('topics_name_key', 'topics', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('topics_name_key', 'topics', ['name'])
    op.add_column('tasks', sa.Column('in_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('type_check', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('out_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'solutions')
    op.drop_column('tasks', 'examples')
    op.drop_column('tasks', 'examples_hidden')
    op.drop_column('tasks', 'api_check')
    # ### end Alembic commands ###
