"""All For AutoCompiles

Revision ID: 8c83cc9c08db
Revises: bef83321bcf3
Create Date: 2020-11-02 03:08:07.299849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c83cc9c08db'
down_revision = 'bef83321bcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('solution_info', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('memory_mb', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('time_sec', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_sec')
    op.drop_column('tasks', 'memory_mb')
    op.drop_column('solutions', 'solution_info')
    # ### end Alembic commands ###
