"""tasks +language

Revision ID: b346e34b1b42
Revises: 87935a2868c7
Create Date: 2020-10-26 02:53:21.092213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b346e34b1b42'
down_revision = '87935a2868c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('language', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'language')
    # ### end Alembic commands ###
