"""SolutionBatch

Revision ID: bbf6f8e96127
Revises: 69f00d6deeb7
Create Date: 2020-11-03 23:38:26.616100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf6f8e96127'
down_revision = '69f00d6deeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.Column('accepted_tasks_count', sa.Integer(), nullable=True),
    sa.Column('failed_tasks_count', sa.Integer(), nullable=True),
    sa.Column('all_tasks_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('submissions', sa.Column('submissions_batch_id', sa.Integer(), nullable=True))
    op.drop_constraint('submissions_solution_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'submissions_batch', ['submissions_batch_id'], ['id'])
    op.drop_column('submissions', 'solution_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('solution_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_solution_id_fkey', 'submissions', 'solutions', ['solution_id'], ['id'])
    op.drop_column('submissions', 'submissions_batch_id')
    op.drop_table('submissions_batch')
    # ### end Alembic commands ###
