"""rename contest_system_to_pupil(pupil_id, contest_system_id)

Revision ID: be5badaa8f1c
Revises: bf272b4d3987
Create Date: 2020-12-31 08:16:13.863973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5badaa8f1c'
down_revision = 'bf272b4d3987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_system_to_pupil', sa.Column('contest_system_id', sa.Integer(), nullable=False))
    op.add_column('contest_system_to_pupil', sa.Column('id_on_contest_system', sa.String(length=200), nullable=True))
    op.drop_constraint('contest_system_to_pupil_service_id_fkey', 'contest_system_to_pupil', type_='foreignkey')
    op.create_foreign_key(None, 'contest_system_to_pupil', 'contest_systems', ['contest_system_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contest_system_to_pupil', 'service_id')
    op.drop_column('contest_system_to_pupil', 'id_on_service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_system_to_pupil', sa.Column('id_on_service', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('contest_system_to_pupil', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contest_system_to_pupil', type_='foreignkey')
    op.create_foreign_key('contest_system_to_pupil_service_id_fkey', 'contest_system_to_pupil', 'contest_systems', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contest_system_to_pupil', 'id_on_contest_system')
    op.drop_column('contest_system_to_pupil', 'contest_system_id')
    # ### end Alembic commands ###
