"""Delete subject

Revision ID: d02a43f170c3
Revises: be5badaa8f1c
Create Date: 2021-01-04 04:48:27.909074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02a43f170c3'
down_revision = 'be5badaa8f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_to_subject')
    op.drop_constraint('groups_subject_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'subject_id')
    op.drop_table('subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_subject_id_fkey', 'groups', 'subjects', ['subject_id'], ['id'])
    op.create_table('teacher_to_subject',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='teacher_to_subject_subject_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teacher_to_subject_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id', name='teacher_to_subject_pkey')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey'),
    sa.UniqueConstraint('name', name='subjects_name_key')
    )
    # ### end Alembic commands ###
