"""lesson_to_group: +(available_from, seconts_to_deadline) -deadline

Revision ID: fc001a82769e
Revises: d4a816f945c2
Create Date: 2021-01-23 23:19:01.250097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc001a82769e'
down_revision = 'd4a816f945c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_to_group', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('lesson_to_group', sa.Column('seconds_to_deadline', sa.Integer(), nullable=True))
    op.drop_column('lesson_to_group', 'deadline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_to_group', sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('lesson_to_group', 'seconds_to_deadline')
    op.drop_column('lesson_to_group', 'available_from')
    # ### end Alembic commands ###
