from . import user
from . import pupil
from . import teacher
from . import subject
from . import course
from . import task
from . import submission
from . import lesson
from . import group
from . import contest_system

from .user import *
from .pupil import *
from .teacher import *
from .subject import *
from .course import *
from .task import *
from .submission import *
from .lesson import *
from .group import *
from .contest_system import *